#!/bin/bash
PATNUM=5

make > make.log

if [ -d "outputResult" ]; then
    rm -rf outputResult
fi
if [ -d "checkResult" ]; then
    rm -rf checkResult
fi
mkdir outputResult
mkdir checkResult
# Jimmy_Testcase
mkdir outputResult/Jimmy_Testcase
echo -e "\033[0;34mJimmy_Testcase\033[0m"
for((i = 1; i <= 6; i = i+1)) do
    ./312510224.o testcase/Jimmy_Testcase/input${i}.txt outputResult/Jimmy_Testcase/output${i}.txt
    ./verifier testcase/Jimmy_Testcase/tmp/output${i}.txt outputResult/Jimmy_Testcase/output${i}.txt  > checkResult/check.log
    if grep -i -q "congratulations, correct answer!" "checkResult/check.log"; then
        echo -e "\033[0;34mPass  \033[m  \033[0;32mPattern No.$i "
    else
        echo -e "\033[31m--- Check Fail ---\033[0m"
        rm -f make.log
    fi
done

# OpenCase
mkdir outputResult/OpenCase
echo -e "\033[0;34mOpenCase\033[0m"
for((i = 1; i <= 6; i = i+1)) do
    ./312510224.o testcase/OpenCase/input${i}.txt outputResult/OpenCase/output${i}.txt
    ./verifier testcase/OpenCase/output${i}.txt outputResult/OpenCase/output${i}.txt  > checkResult/check.log
    if grep -i -q "congratulations, correct answer!" "checkResult/check.log"; then
        echo -e "\033[0;34mPass  \033[m  \033[0;32mPattern No.$i "
    else
        echo -e "\033[31m--- Check Fail ---\033[0m"
        rm -f make.log
    fi
done

echo -e "\033[0;32mCongratulation!! You have passed all patterns. \033[0m"

rm -f make.log